import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

const IBMPlexSans = IBM_Plex_Sans({
  weight: "400",
  variable: "--font-ibm-sans",
  subsets: ["latin"],
});

const IBMPlexMono = IBM_Plex_Mono({
  weight: "400",
  variable: "--font-ibm-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${IBMPlexSans.variable} ${IBMPlexMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
